application: mogu-img
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /image
  static_dir: image
- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "1d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static
  expiration : "1d"
  secure: optional

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.3"
- name: markupsafe
  version: "0.15"